import type { Agent, Ticket } from '../types/types';
export const MOCK_TICKETS: Ticket[] = [
  {
    ticketId: 101,
    title: 'Unable to log in',
    description: 'Alice Carter cannot sign in and needs account access support.',
    type: 'TECH_SUPPORT',
    status: 'OPEN',
    createdAt: '2026-04-12T10:30:00Z',
    updatedAt: '2026-04-13T17:12:00Z',
    customer: 'Alice Carter',
    assignedAgentId: 1,
    priority: 'High',
    messages: [
      { messageId: 1, content: "I can't log in on chrome.", sender: "user", sentAt: "4/7/26 09:00" },
      { messageId: 2, content: "Are you getting any error codes?", sender: "agent", sentAt: "4/7/26 09:15" },
      { messageId: 3, content: "test message ", sender: "user", sentAt: "4/7/26 09:20" },
      { messageId: 4, content: "test 2", sender: "user", sentAt: "4/7/26 09:20" },

      { messageId: 5, content: "please give team 3 an A ", sender: "agent", sentAt: "4/7/26 09:25" }, //lol
      { messageId: 6, content: "yeah", sender: "user", sentAt: "4/7/26 09:30" },
    ],
    statusHistory: [
      { id: 1, oldStatus: "OPEN", newStatus: "IN_PROGRESS", changedBy: "Agent Smith", changedAt: "4/7/26 09:10" },
    ],
  },
  {
    ticketId: 102,
    title: 'ISSUE 1',
    description: 'Customer1 reported a login-related bug and requested assistance.',
    type: 'BUG',
    status: 'IN_PROGRESS',
    createdAt: '2026-04-11T14:15:00Z',
    updatedAt: '2026-04-11T20:10:00Z',
    customer: 'Customer1',
    assignedAgentId: 2,
    priority: 'Medium',
    messages: [],
    statusHistory: [],
  },
  {
    ticketId: 103,
    title: 'Billing question',
    description: 'Brian Lee has a billing question about his latest invoice.',
    type: 'BILLING',
    status: 'IN_PROGRESS',
    createdAt: '2026-04-10T09:00:00Z',
    updatedAt: '2026-04-11T22:38:00Z',
    customer: 'Brian Lee',
    assignedAgentId: 3,
    priority: 'Low',
    messages: [],
    statusHistory: [],
  },
  {
    ticketId: 104,
    title: 'Account verification problem',
    description: 'Dana Fox is blocked by account verification and needs follow-up.',
    type: 'ACCOUNT',
    status: 'OPEN',
    createdAt: '2026-04-09T16:45:00Z',
    updatedAt: '2026-04-12T12:32:00Z',
    customer: 'Dana Fox',
    assignedAgentId: null,
    priority: 'High',
    messages: [],
    statusHistory: [],
  },
  {
    ticketId: 105,
    title: 'Phone number update fails',
    description: 'Saving new phone number succeeds in UI but does not persist.',
    type: 'ACCOUNT',
    status: 'RESOLVED',
    createdAt: '2026-04-08T11:20:00Z',
    updatedAt: '2026-04-08T21:29:00Z',
    customer: 'Unknown User',
    assignedAgentId: 1,
    priority: 'Medium',
    messages: [],
    statusHistory: [],
  },
  {
    ticketId: 106,
    title: 'Mobile push notifications missing',
    description: 'Push notifications are not received on mobile after update.',
    type: 'BUG',
    status: 'CLOSED',
    createdAt: '2026-04-07T13:00:00Z',
    updatedAt: '2026-04-07T20:19:00Z',
    customer: 'Unknown User',
    assignedAgentId: 2,
    priority: 'Low',
    messages: [],
    statusHistory: [],
  },
  {
    ticketId: 107,
    title: 'Login fails on Chrome',
    description: "I can't log in on Chrome and need help resolving the browser-specific issue.",
    type: 'BUG',
    status: 'OPEN',
    createdAt: '2026-04-07T09:00:00Z',
    updatedAt: '2026-04-09T03:10:00Z',
    customer: 'Unknown User',
    assignedAgentId: null,
    priority: 'High',
    messages: [],
    statusHistory: [],
  },
  {
    ticketId: 108,
    title: 'CSV export empty',
    description: 'Export to CSV creates an empty file for any filter.',
    type: 'TECH_SUPPORT',
    status: 'IN_PROGRESS',
    createdAt: '2026-04-06T08:30:00Z',
    updatedAt: '2026-04-09T07:12:00Z',
    customer: 'Unknown User',
    assignedAgentId: 3,
    priority: 'Medium',
    messages: [],
    statusHistory: [],
  },
  {
    ticketId: 109,
    title: 'Add dark mode to app',
    description: 'Feature request to provide dark mode support throughout the application.',
    type: 'FEATURE_REQUEST',
    status: 'IN_PROGRESS',
    createdAt: '2026-04-06T09:00:00Z',
    updatedAt: '2026-04-06T17:20:00Z',
    customer: 'Product Team',
    assignedAgentId: 1,
    priority: 'Low',
    messages: [],
    statusHistory: [],
  },
  {
    ticketId: 110,
    title: 'Onboarding help request',
    description: 'Need setup guidance for five new team members.',
    type: 'OTHER',
    status: 'OPEN',
    createdAt: '2026-04-05T15:45:00Z',
    updatedAt: '2026-04-06T06:26:00Z',
    customer: 'Operations Team',
    assignedAgentId: 2,
    priority: 'Medium',
    messages: [],
    statusHistory: [],
  },
  {
    ticketId: 111,
    title: 'Safari chart rendering issue',
    description: 'Dashboard charts fail to render in Safari 17.',
    type: 'BUG',
    status: 'OPEN',
    createdAt: '2026-04-04T10:00:00Z',
    updatedAt: '2026-04-07T07:03:00Z',
    customer: 'Unknown User',
    assignedAgentId: 3,
    priority: 'High',
    messages: [],
    statusHistory: [],
  },
  {
    ticketId: 112,
    title: 'Missing invoice email',
    description: 'Invoice was not generated or emailed for prior cycle.',
    type: 'BILLING',
    status: 'WAITING_ON_CUSTOMER',
    createdAt: '2026-04-03T12:30:00Z',
    updatedAt: '2026-04-03T14:19:00Z',
    customer: 'Finance User',
    assignedAgentId: null,
    priority: 'Medium',
    messages: [],
    statusHistory: [],
  },
  {
    ticketId: 113,
    title: 'Bulk assignment request',
    description: 'Need bulk ticket assignment in queue view.',
    type: 'FEATURE_REQUEST',
    status: 'CLOSED',
    createdAt: '2026-04-02T09:15:00Z',
    updatedAt: '2026-04-03T03:50:00Z',
    customer: 'Admin User',
    assignedAgentId: 1,
    priority: 'Low',
    messages: [],
    statusHistory: [],
  },
  {
    ticketId: 114,
    title: '2FA issue',
    description: 'Two-factor auth codes from third-party app are rejected.',
    type: 'ACCOUNT',
    status: 'RESOLVED',
    createdAt: '2026-04-01T14:00:00Z',
    updatedAt: '2026-04-02T21:05:00Z',
    customer: 'Security User',
    assignedAgentId: 2,
    priority: 'High',
    messages: [],
    statusHistory: [],
  },
  {
    ticketId: 115,
    title: 'Duplicate search results',
    description: 'Search results show duplicate entries after deployment.',
    type: 'BUG',
    status: 'IN_PROGRESS',
    createdAt: '2026-03-31T11:45:00Z',
    updatedAt: '2026-04-02T07:20:00Z',
    customer: 'Unknown User',
    assignedAgentId: 3,
    priority: 'Medium',
    messages: [],
    statusHistory: [],
  },
  {
    ticketId: 116,
    title: 'Rate limit errors',
    description: 'Integration endpoints return rate limit errors immediately.',
    type: 'TECH_SUPPORT',
    status: 'OPEN',
    createdAt: '2026-03-30T16:20:00Z',
    updatedAt: '2026-03-30T17:23:00Z',
    customer: 'Developer User',
    assignedAgentId: null,
    priority: 'High',
    messages: [],
    statusHistory: [],
  },
  {
    ticketId: 117,
    title: 'Company name update',
    description: 'Need organization name changed across all views.',
    type: 'OTHER',
    status: 'CLOSED',
    createdAt: '2026-03-29T10:00:00Z',
    updatedAt: '2026-03-30T08:53:00Z',
    customer: 'Company Admin',
    assignedAgentId: 1,
    priority: 'Low',
    messages: [],
    statusHistory: [],
  },
  {
    ticketId: 118,
    title: 'Timezone filter mismatch',
    description: 'Date range filter ignores user timezone settings.',
    type: 'BUG',
    status: 'RESOLVED',
    createdAt: '2026-03-28T13:30:00Z',
    updatedAt: '2026-03-28T18:03:00Z',
    customer: 'Unknown User',
    assignedAgentId: 2,
    priority: 'Medium',
    messages: [],
    statusHistory: [],
  },
  {
    ticketId: 119,
    title: 'Payment method validation',
    description: 'Unable to add new payment method due to validation loop.',
    type: 'BILLING',
    status: 'OPEN',
    createdAt: '2026-03-27T09:00:00Z',
    updatedAt: '2026-03-29T03:50:00Z',
    customer: 'Billing User',
    assignedAgentId: 3,
    priority: 'High',
    messages: [],
    statusHistory: [],
  },
  {
    ticketId: 120,
    title: 'Weekly digest request',
    description: 'Need weekly email digest with ticket and SLA summary.',
    type: 'FEATURE_REQUEST',
    status: 'WAITING_ON_CUSTOMER',
    createdAt: '2026-03-26T15:00:00Z',
    updatedAt: '2026-03-28T14:43:00Z',
    customer: 'Manager User',
    assignedAgentId: null,
    priority: 'Low',
    messages: [],
    statusHistory: [],
  },
  {
    ticketId: 121,
    title: 'Webhook events missing',
    description: 'Webhook integration does not fire on ticket creation.',
    type: 'TECH_SUPPORT',
    status: 'IN_PROGRESS',
    createdAt: '2026-03-25T11:00:00Z',
    updatedAt: '2026-03-28T00:33:00Z',
    customer: 'Integration User',
    assignedAgentId: 1,
    priority: 'High',
    messages: [],
    statusHistory: [],
  },
  {
    ticketId: 122,
    title: 'Account lockout with SSO',
    description: 'Account locked after failed login attempts using SSO.',
    type: 'ACCOUNT',
    status: 'CLOSED',
    createdAt: '2026-03-24T14:30:00Z',
    updatedAt: '2026-03-26T21:18:00Z',
    customer: 'SSO User',
    assignedAgentId: 2,
    priority: 'Medium',
    messages: [],
    statusHistory: [],
  }
];

export const MOCK_AGENTS: Agent[] = [
  { id: 1, name: "Agent Smith" },
  { id: 2, name: "Agent Johnson" },
  { id: 3, name: "Agent Lee" },
];